name: Auto approve

on:
  pull_request:
    types: [opened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'Gitii'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
