name: Validate PRs and Main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2
      - run: |
          dotnet tool restore
          dotnet csharpier --check

  execute_tests:
    runs-on: windows-2022
    name: Execute tests
    strategy:
      matrix:
        platform: ["x86", "x64", "arm64"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure SSH agent to allow access to private submodules
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.WINSTRUMENTA_E2E_SSH_PRIVATE_KEY }}
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
          vs-version: 17
          vs-prerelease: true
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      - name: Build
        run: msbuild /m /t:build /restore /p:Configuration=Release /p:Platform=${{ matrix.platform }} /p:AppxPackage=false /m Winstrumenta.sln
      - name: Test
        run: Get-ChildItem -Recurse -Filter "*.Tests.dll" | ? { $_.FullName -Match "bin.[^.]+.Release" -and $_.FullName -notmatch "ref" } | % { vstest.console.exe $_.FullName }
